###############################################################################
# Provisionous Docker/Puppet profile
# OS: Fedora 19 (schrodinger)
# Equivalent: RHEL 7, CentOS 7 (centos7)
###############################################################################

FROM fedora:schrodinger
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

