###############################################################################
# Custom Docker/Puppet profile
# OS: Debian 6 (squeeze)
# Equivalent: Ubuntu 10.04 (lucid)
###############################################################################

FROM solict/provisionous-puppet-debian:squeeze

