###############################################################################
# Docker profile
# OS: CentOS 5 (centos5)
# Equivalent: RHEL 5, Fedora 6 (zod)
###############################################################################

FROM centos:centos5
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

