###############################################################################
# Custom Docker/Puppet profile
# OS: Ubuntu 12.04 (trusty) RVM
# Equivalent: Debian 8 (jessie)
###############################################################################

FROM solict/provisionous-puppet-ubuntu:trusty_rvm

