###############################################################################
# Custom Docker/Puppet profile
# OS: CentOS 5 (centos5) RVM
# Equivalent: RHEL 5, Fedora 6 (zod)
###############################################################################

FROM solict/provisionous-puppet-centos:centos5_rvm

