###############################################################################
# Custom Docker/Puppet profile
# OS: Ubuntu 10.04 (lucid) RVM
# Equivalent: Debian 6 (squeeze)
###############################################################################

FROM solict/provisionous-puppet-ubuntu:lucid_rvm

