###############################################################################
# Custom Docker/Puppet profile
# OS: Ubuntu 12.04 (precise)
# Equivalent: Debian 7 (wheezy)
###############################################################################

FROM solict/provisionous-puppet-ubuntu:precise

