###############################################################################
# Docker profile
# OS: Fedora 12 (constantine)
# Equivalent: RHEL 6, CentOS 6 (centos6)
###############################################################################

FROM fedora:constantine
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

