###############################################################################
# Provisionous Docker/Puppet profile
# OS: Fedora 6 (zod)
# Equivalent: RHEL 5, CentOS 5 (centos5)
###############################################################################

FROM fedora:zod
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

