###############################################################################
# Provisionous Docker/Puppet profile
# OS: Ubuntu 12.04 (trusty)
# Equivalent: Debian 8 (jessie)
###############################################################################

FROM ubuntu:trusty
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

