###############################################################################
# Custom Docker/Puppet profile
# OS: Debian 7 (wheezy) RVM
# Equivalent: Ubuntu 12.04 (precise)
###############################################################################

FROM solict/provisionous-puppet-debian:wheezy_rvm

