###############################################################################
# Custom Docker/Puppet profile
# OS: Debian 8 (jessie) RVM
# Equivalent: Ubuntu 12.04 (trusty)
###############################################################################

FROM solict/provisionous-puppet-debian:jessie_rvm

