###############################################################################
# Provisionous Docker/Puppet profile
# OS: Ubuntu 12.04 (precise)
# Equivalent: Debian 7 (wheezy)
###############################################################################

FROM ubuntu:precise
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

