###############################################################################
# Custom Docker/Puppet profile
# OS: CentOS 7 (centos7)
# Equivalent: RHEL 7, Fedora 19 (schrodinger)
###############################################################################

FROM solict/provisionous-puppet-centos:centos7

