###############################################################################
# Docker profile
# OS: CentOS 6 (centos6)
# Equivalent: RHEL 6, Fedora 12 (constantine)
###############################################################################

FROM centos:centos6
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

