###############################################################################
# Provisionous Docker/Puppet profile
# OS: CentOS 7 (centos7)
# Equivalent: RHEL 7, Fedora 19 (schrodinger)
###############################################################################

FROM centos:centos7
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

