###############################################################################
# Custom Docker/Puppet profile
# OS: CentOS 6 (centos6)
# Equivalent: RHEL 6, Fedora 12 (constantine)
###############################################################################

FROM solict/provisionous-puppet-centos:centos6

