###############################################################################
# Custom Docker/Puppet profile
# OS: Ubuntu 12.04 (precise) RVM
# Equivalent: Debian 7 (wheezy)
###############################################################################

FROM solict/provisionous-puppet-ubuntu:precise_rvm

