###############################################################################
# Docker profile
# OS: Ubuntu 10.04 (lucid)
# Equivalent: Debian 6 (squeeze)
###############################################################################

FROM ubuntu:lucid
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

