###############################################################################
# Docker profile
# OS: Debian 6 (squeeze)
# Equivalent: Ubuntu 10.04 (lucid)
###############################################################################

FROM debian:squeeze
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

