###############################################################################
# Docker profile
# OS: Debian 7 (wheezy)
# Equivalent: Ubuntu 12.04 (precise)
###############################################################################

FROM debian:wheezy
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

