###############################################################################
# Docker profile
# OS: Debian 8 (jessie)
# Equivalent: Ubuntu 12.04 (trusty)
###############################################################################

FROM debian:jessie
MAINTAINER Luís Pedro Algarvio <lp.algarvio@gmail.com>

